version: "2"
services:
  gunicorn_nginx:
    restart: always
    image: registry.time-track.cn:8081/library/payment_nginx:1.0
    networks:
      - payment
    depends_on:
      - payment
    environment:
      - BACKEND=payment:8000
    ports:
      - "8081:80"
  payment:
    restart: always
    image: registry.time-track.cn:8081/library/payment:1.1.10
    networks:
      - payment
    depends_on:
      - mysql
      - redis
    volumes:
      - runtime_data:/Payment/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - IS_MASTER=0
      - MYSQL_USER=root
      - MYSQL_DATABASE_NAME=caas_payment
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=10.0.128.201
      - MYSQL_PORT=3306
      - PUBLIC_HOST=54.223.117.211
      - PUBLIC_PORT=8081
      - RANCHER_URL=http://10.0.117.140:3000/v1-usage/account/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ALERT_URL=http://10.0.128.200/mc/v1/message/receive/
      - API_KEY=0D02C551372B79DE6E68
      - API_PASS=G4kqtMgJXndw8K5gfMjdnPTbDYNiWRTuiGsJmTgn
      - USER_SYSTEM_URL=http://10.0.128.199:8081/v1/projects/user/authentication
    ports:
      - "8000"
  redis:
    restart: always
    networks:
      - payment
    image: redis
networks:
  payment:
    external: false
volumes:
  runtime_data:
    external: false


